export const data = [
    {
        id: "1",
        category: "guitarras",
        nombre: "Guitarra",
        marca: "Yamaha",
        precio: 110000,
        imagen: "guitarra-yamaha",
        modelo: "012",
        tipo: "Eléctrica",
        color: "Blanco",
        estado: "Nuevo",
        material: "Caoba",
        video: "https://www.youtube.com/embed/a3GY9evykP8"
    },
    {
        id: "2",
        nombre: "Bajo",
        category: "bajos",
        marca: "Texas",
        precio: 120000,
        imagen: "bajo-texas",
        modelo: "E81",
        tipo: "Jazz Bass",
        color: "Negro",
        estado: "Usado",
        material: "Caoba",
        video: "https://www.youtube.com/embed/H6iA-CqZkws"

    },
    {
        id: "3",
        category: "baterias",
        nombre: "Bateria",
        marca: "Mapex",
        precio: 130000,
        imagen: "bateria-mapex",
        modelo: "Voyager",
        tipo: "Acústica",
        color: "Azul",
        estado: "Nuevo",
        material: "Maple",
        video: "https://www.youtube.com/embed/FGREAA9UuzI"
    },
    {
        id: "4",
        category: "guitarras",
        nombre: "Guitarra criolla",
        marca: "Taylor",
        precio: 140000,
        imagen: "guitarra-taylor",
        modelo: "Custom series",
        tipo: "Acustica",
        color: "Natural",
        estado: "Nuevo",
        material: "Caoba",
        video: "https://www.youtube.com/embed/keocn_RPVPc"
    },
    {
        id: "5",
        nombre: "Violin",
        category: "violines",
        marca: "Stradivarius",
        precio: 150000,
        imagen: "violin",
        modelo: "F420",
        tipo: "Elecctrico",
        color: "Natural",
        estado: "Nuevo",
        material: "Caoba",
        video: "https://www.youtube.com/embed/4AunXw3GiWs"
    },
    {
        id: "6",
        nombre: "Bateria",
        category: "baterias",
        marca: "Roland",
        precio: 250000,
        imagen: "bateria-roland",
        modelo: "VAD-306",
        tipo: "Midi",
        color: "Negro",
        estado: "Nuevo",
        material: "Metal y pads de goma",
        video: "https://www.youtube.com/embed/4AunXw3GiWs"
    },
    {
        id: "7",
        nombre: "Bajo",
        category: "bajos",
        marca: "Yamaha",
        precio: 350000,
        imagen: "bajo-acustico",
        modelo: "V2D-406",
        tipo: "Acústico",
        color: "Natural",
        estado: "Nuevo",
        material: "Madera brillante",
        video: "https://www.youtube.com/embed/4AunXw3GiWs"
    },
    {
        id: "8",
        nombre: "Cajon peruano",
        category: "percusion",
        marca: "Gaucho",
        precio: 50000,
        imagen: "cajon-peruano",
        modelo: "TG35-1",
        tipo: "Percusion",
        color: "Madera",
        estado: "Nuevo",
        material: "Caoba",
        video: "https://www.youtube.com/embed/4AunXw3GiWs"
    },
    {
        id: "9",
        nombre: "Bombo leguero",
        category: "percusion",
        marca: "Gaucho",
        precio: 30000,
        imagen: "bombo-leguero",
        modelo: "1235-57",
        tipo: "Percusion",
        color: "Madera",
        estado: "Nuevo",
        material: "Madera con parche tensado",
        video: "https://www.youtube.com/embed/4AunXw3GiWs"
    },
    {
        id: "10",
        nombre: "Contrabajo",
        category: "cuerdas",
        marca: "Etinger Standard",
        precio: 320000,
        imagen: "contrabajo",
        modelo: "1235-5HH",
        tipo: "Acústico",
        color: "Madera",
        estado: "Nuevo",
        material: "Caoba",
        video: "https://www.youtube.com/embed/4AunXw3GiWs"
    },
]