export const data = [
    {
        id: 1,
        category: "guitarras",
        nombre: "Guitarra",
        marca: "Yamaha",
        precio: "110.000",
        imagen: "guitarra-yamaha",
        modelo:"012",
        tipo : "PAC012/100 Series",
        construccion: "Mástil atornillado al cuerpo",
        cuerpo: "Caoba",
        cuello: "Maple",
        diapason: "Palo de rosa",
        trastes: "22 trastes ",
        microfonos: "Humbucker, Simple",
        controles: "Selector de micrófonos, Tono, Volumen",
        clavijero: "Custom",
    },
    {
        id: 2,
        nombre: "Bajo",
        category: "bajos",
        marca: "Texas",
        precio: "120.000",
        imagen: "bajo-texas",
        modelo:"E81",
        tipo : "Jazz Bass",
        construccion: "Mástil atornillado al cuerpo",
        cuerpo: "Basswood",
        cuello: "Maple",
        diapason: "Palo de rosa",
        trastes: "21 trastes cromados",
        microfonos: "2 jazz bass de bobinado sencillo",
        controles: "1 volumen y 1 tono",
        clavijero: "Estilo clásico de bajo",
    },
    {
        id: 3,
        category: "baterias",
        nombre: "Bateria",
        marca: "Mapex",
        precio: "130.000",
        imagen: "bateria-mapex",
        modelo:"Voyager",
        tipo : "Acústica",
        construccion: "Maple",
        cuerpo: "Cinco cuerpos",
        cuello: "No corresponde",
        diapason: "No corresponde",
        trastes: "No corresponde",
        microfonos: "No corresponde",
        controles: "No corresponde",
        clavijero: "No corresponde",
    },
    {
        id: 4,
        category: "guitarras",
        nombre: "Guitarra criolla",
        marca: "Taylor",
        precio: "140.000",
        imagen: "guitarra-taylor",
        modelo:"Custom series",
        tipo : "Acustica",
        construccion: "Mástil atornillado al cuerpo",
        cuerpo: "Caoba",
        cuello: "Maple",
        diapason: "Palo de rosa",
        trastes: "18 trastes ",
        microfonos: "No posee",
        controles: "Manuales",
        clavijero: "Custom",  
    },
    {
        id: 5,
        nombre: "Violin",
        category: "violines",
        marca: "Acme",
        precio: "150.000",
        imagen: "violin",
        modelo:"F420",
        tipo : "Elecctrico",
        construccion: "Mástil atornillado al cuerpo",
        cuerpo: "Caoba",
        cuello: "Maple",
        diapason: "Palo de rosa",
        trastes: "16 trastes ",
        microfonos: "Simples",
        controles: "Volumen",
        clavijero: "Tradicional",  
    }
]